### ISSUE TITLE
Продумать архитектуру приложения

### ISSUE THREAD

**Issue by JorJeG** [completed-actions/todo-for-you#1]
# Первые шаги
Минимальные требования:
- добавить линтеры, editorconfig
- создать фронт через create-react-app
@completed-actions/t3

**Comment by belodpav** [comment]
Про линтеры не все пока очевидно. 
Как я понимаю в create-react-app свои линтеры стоят. Нам надо как-то избежать это конфликта.
Как вариант добавить в .elsintignore клиентскую часть. Либо настроить create-react-app линтеры под наш код стайл

**Comment by dezmound** [comment]
@belodpav Наверное норм вариант только package.json объединить бэка с фронтом. Линтеры в директориях (`client` и `server` (условно)) пусть свои будут, просто в `package.json` добавить строчки типа:
```json
{
    "scripts": {
           "lint:front": "eslint client --config client/.eslint && stylelint client --config client/.stylelint",
           "lint:back": "eslint server --config server/.eslint",
           "lint": "npm run lint:front && npm run lint:back"
    }
}
```

**Comment by JorJeG** [comment]
я посмотрел разные репозитории, 1 из 3 не в пользу объединения package.json для бэка с фронтом

**Comment by JorJeG** [comment]
Mock чтобы сделать свою архитектуру, и добавить её  в README
```
my-app
├── README.md
├── node_modules
├── package.json
├── .gitignore
├── public
│   └── favicon.ico
│   └── index.html
│   └── manifest.json
└── src
    └── App.css
    └── App.js
    └── App.test.js
    └── index.css
    └── index.js
    └── logo.svg
    └── registerServiceWorker.js
```

**Comment by belodpav** [comment]
https://github.com/completed-actions/todo-for-you/tree/issue-1

**Comment by JorJeG** [comment]
@belodpav 
Вроде это будет достаточно для eslint, добавил поддержку jsx
```
{
  "extends": "google",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
  }
  }
}
```

**Comment by belodpav** [comment]
Как бороться с ошибкой линтера 
`'React' is defined but never used. (no-unused-vars) `
?

**Comment by dezmound** [comment]
// eslint-disable no-unused-vars
А зачем вообще в реки эта переменная импортируется?

**Comment by belodpav** [comment]
@dezmound  Решил вопрос.

**Comment by belodpav** [comment]
@JorJeG  в Ректе встроен stylelint?

**Comment by JorJeG** [comment]
нет, добавляем как обычно через
```
yarn add -D stylelint stylelint-config-standard
```

**Comment by JorJeG** [comment]
Я говорил @dezmound когда устанавливаем зависимости для client, то пользуемся yarn, либо все lock файлы добавляем в .gitignore, чтобы потом не было конфликта yarn/npm

**Comment by JorJeG** [comment]
React импортируется для того, чтобы в файле можно было использовать jsx

**Comment by belodpav** [comment]
@JorJeG  А зачем нам yarn?

**Comment by JorJeG** [comment]
@belodpav Он по дефолту от create-react-app идёт

**Comment by belodpav** [comment]
@JorJeG  Можно по подробнее, где это прописано?
Просто я вижу только package.json без yarnoв. 
И пока, вроде, не было необходимотси в нем.

**Comment by JorJeG** [comment]
@belodpav Да, я посмотрел у тебя почему-то create-react-app установил зависимости через npm, это для меня странно. Ты сделал приложение командой?
```
npx create-react-app my-app
```

**Comment by belodpav** [comment]
@JorJeG Нет, я устанавливал через глобальную утилиту

**Comment by JorJeG** [comment]
Мужики круто! Первые шаги! Растём!
