### ISSUE TITLE
Изменение архитектуры клиентского приложения 

### ISSUE THREAD

**Issue by belodpav** [completed-actions/todo-for-you#16]
Предлагаю изменить архитектурный подход к построению компонентов приложения,
раньше: контейнеры компонентов выделяли в отдельную папку containers
теперь: "контейнер" это одна из технологий в которых будем реализовывать компонент
```
components/
    ...
    Button/
        Button.css - стили к компоненту
        Button.test.js - Тесты к компоненту
        Button.md - документация к компоненту
        Button.html - демонстрация компонента на странице
        Button.view.js - верстка, навешивание событий на элеметы
        Button.js  - логика, получение.обработка данных, событий и т.д.

```

Мы как бы разрабатываем компонент в многомерном пространстве технологий: css, test.js, md, html, и т.д.

**Comment by dezmound** [comment]
@belodpav Хорошее предложение, я за.
