### ISSUE TITLE
Настройка Storybook для create-react-app

### ISSUE THREAD

**Issue by belodpav** [completed-actions/todo-for-you#19]
Использование Storybook позволит вести **независимую разработку компонентов** приложения я одновременно составлять документацию в наглядной форме.

**Comment by belodpav** [comment]
Если не ошибаюсь вчера порешали все по этому вопросу.
Думаю, надо закрыть, т.к. настроили storybook => задача выполнена
Закрываем?

**Comment by JorJeG** [comment]
Закрываем
