### ISSUE TITLE
Добавление в eslint новых правил

### ISSUE THREAD

**Issue by JorJeG** [completed-actions/todo-for-you#21]
Google config отключает правило про неиспользуемые аргументы в функции, добавляем?
```
  createUser(root, {input}, context) {
    return models.User.create(input);
  },
```

**Comment by JorJeG** [comment]
```
{
    "extends": ["eslint:recommended", "google"],
    "env": {
        "node": true,
        "mocha": true,
        "es6": true
    },
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module"
    },
    "rules": {
        "comma-dangle": [2, "never"],
        "new-cap": [2, { "capIsNew": false }],
        "no-unused-vars": [2, { "vars": "all", "args": "after-used" }]
    }
}
```

**Comment by dezmound** [comment]
@JorJeG норм конфиг, одобряю.

**Comment by JorJeG** [comment]
Его зальём в #4 , с тэгом (config)? пока такого коммита не вижу

**Comment by dezmound** [comment]
Ну в принципе можно, но можно и создать ветку с номером 21. И ее влить в dev.

**Comment by belodpav** [comment]
Секунду, а зачем нам не используемые аргументы у функции?
```
 createUser(root, {input}, context) {
    return models.User.create(input);
  },
```
context надо удалять здесь
Это в каком файле?

**Comment by dezmound** [comment]
@belodpav Я уже удалил. #13

**Comment by belodpav** [comment]
Красава. Тогда в этом rule отпадает необходимость?
Чтобы нам не собирать "мусора" в коде

**Comment by JorJeG** [comment]
Без этого rules у нас бы залилось c context, который мы не используем, я просто случайно заметил

**Comment by dezmound** [comment]
Без этого правила возможно в будущем появятся неиспользуемые параметры.

**Comment by belodpav** [comment]
А ну ништяк тогда. Я думал мы собираемся отключить это правило

**Comment by belodpav** [comment]
тогда мержим
