### ISSUE TITLE
Связка [X-database]-Sequelize-Graphql на сервере

### ISSUE THREAD

**Issue by JorJeG** [completed-actions/todo-for-you#4]
# Разработка бэкенда
На выходе должны получить готовый сервер, который по localhost:3001/graphql выполняет все поставленные задачи на бэке(добавление пользователя в БД при авторизации, добавление Todo и Task у пользователя, добавление друзей к пользователю, удаление Task из Todo, удаление Todo, изменение title у Todo/Task, изменение состояние Task, изменение приоритета Todo)

- [x] Схема graphql
- [x] Обработка всех запросов в graphql/resolvers

Опционально: 
- [ ] [Subscription](https://github.com/apollographql/graphql-subscriptions)
- [x] Выбрать БД и указать это в Sequelize, либо оставить как есть

**Comment by belodpav** [comment]
Предлагаю подумать над:
1. Выбором БД. Предполагаю,если будет использоваться mongoDB, то sequelize не понадобится.
БД уже выбрали?
2. Не слишком ли большая задача на один issue? Сейчас всплывает аналогия: issue-1 - разработка приложения.( на выходе должны получить приложение). Разбиение задачи на подзадачи это very good, если конечно все обосновано. Наврное, я что-то неправильно понял из названия, поэтому прошу поправить.

**Comment by dezmound** [comment]
@belodpav Да действительно, если будем использовать `MongoDB` нам не нужен будет `sequilize`. Но я обеими лапами за реляционку.     
Если сделать топ-3 кандидатов то в моем представлении это что то такое:    
- PostgreSql
- SqlLite
- MySql

**Comment by belodpav** [comment]
@dezmound Отлично! Тогда берем что-нибудь из списка. 
 У тебя есть опыт работы с БД из этого списка?

**Comment by JorJeG** [comment]
@belodpav Одну подзадачу мы уже открывали в #3 и её решили
можно открыть другие issue, а эту оставить как обсуждение на общую тему,
но тогда для неё не нужно было делать ветку и её удалить

**Comment by dezmound** [comment]
@belodpav Да, со всеми. Предлагаю создать файл конфигурации, чтобы на локалке можно было использовать `sqlite`, а в контейнер уже если будет необходимо прокинуть другую СУБД.

**Comment by belodpav** [comment]
@dezmound Поддерживаю данный подход

**Comment by JorJeG** [comment]
Выявилась ошибка, при создании Todo.
Нужно поменять в схеме значение на 
```
createAt: Sequelize.INTEGER
```
и посылать значения TimeStamp в секундах

**Comment by dezmound** [comment]
Надо поправить `Sequelize` схему. Сейчас исправлю.

**Comment by JorJeG** [comment]
#23
