### ISSUE TITLE
Архитектура клиентской части приложения

### ISSUE THREAD

**Issue by JorJeG** [completed-actions/todo-for-you#5]
Постараться продумать:
- названия компонентов/селекторы для классов
- как разложить компоненты по директориям(может стоит разделить на components/containers)

В итоге должна получится библиотека из компонентов с ясными названиями
на основе этого получится распределить задачи вёрстки и дальнейшей разработки функционала

**Comment by belodpav** [comment]
На подумать:
1. Пункты списка "постараться продумать" можно представить как отдельные задачи(issues). Это к тому чтобы не получалось: задача - Разработать приложение, результат - приложение.

**Comment by belodpav** [comment]
Ниже проведена разбивка на независимые переиспользуемые компоненты. 
Дочерние элементы компонентов здесь не выделены(Элементы в БЭМ терминах), предположительно это разбиение будет делать разработчик компонента(????). 
### Header
![todo-for-you__main-320-header](https://user-images.githubusercontent.com/22286720/38923401-1f38d49e-4303-11e8-96aa-7f05f638888c.png)

### List
![todo-for-you__main-320-lists](https://user-images.githubusercontent.com/22286720/38922171-374e8108-4300-11e8-8a00-73cc7cc9f477.png)

Обсуждаем, добавляем, разбиваем.

p.s. мышки нет, рисовать больше не смогу. Поэтому можно писать текстом по типу построения дерева компонентов:
```
Header
    UserPreview
        Avatar
    Button
       Icon
   ....
   and so on.... 
```

**Comment by belodpav** [comment]
Файловая структура клиентского приложения на подобие такой?
В каких технологиях будем разрабатывать компоненты?
Если мы разделяем компоненты на умные и глупые, то будем помещать напрмер тесты для компонента(и какие тесты)?
```
client/
    ....(то что уже есть в папке client)
    components/
        Button/
            Button.js
            Button.css
        Icon/
        ....
    containers/
        Button/
            Button.js
            Button.md
            Button.test.js (???)
        Icon/
        ....



```

**Comment by dezmound** [comment]
@belodpav Я посмотрел еще раз твой репозиторий с 3 вступительным. Подход норм.     
Насчет тестов я думаю что будем использовать jest, например как его используют в этой статье:    [FB Testing Components](https://facebook.github.io/jest/docs/en/tutorial-react.html).

**Comment by dezmound** [comment]
Насчет компонентов. Я думаю стоит добавить еще список с элементами в карточке:
![Компоненты](https://i.imgur.com/ASUUsDA.png)

**Comment by JorJeG** [comment]
Привет! Да впринципе, то что я и хотел тут видеть.
Дополнения:
- есть разные Icon, как мы будем их разделять, у каждого своя логика(три штуки)
- внутри TodoCard, я бы сделал разделение на header, body, чтобы потом легко можно было прятать body, и наверное туда же включил бы NewCardInput

**Comment by belodpav** [comment]
@JorJeG 

1. Есть разные подходы решить этот вопрос. Но компонент лучше сделать один.
2. Да, все верно, но Подчеркну я выделял независимые и переиспользуемые сущности(блоки в терминах БЭМа) От этих сущностей надо будет начинать плясать и разбивать на меньшие компоненты(Элементы ну или что-то в этом роде)

**Comment by belodpav** [comment]
@dezmound  Ништяк, тогда будем юзать jest :)

Да, все верно у нас будут эти компоненты. Частично ответ дан выше

**Comment by JorJeG** [comment]
Чтобы закрыть это issue, нужно открыть ветку c issue и сделать pull request с _пустыми_ папками(т.е всё-таки что-то туда положить, чтобы запушилось на github), дальше я открою новый issue с тасками по верстке, где буду заполнять готовность

**Comment by belodpav** [comment]
Жор, ты хочешь поюзать Storybook? 
Вроде интересная штука. Надо будет посмотреть ее подробнее. 
Выглядит интересно. 
Хотя наврное может быть пока что  просто делать файл button.html в нем писать 
`ReactDOM.render(<Button .... />, ...)` или что-то в этом роде.

Хорошо, чуть позже накидаю структуру папок :+1:

**Comment by JorJeG** [comment]
Я начал было устанавливать Storybook, он что-то гигантское скачивает, может я что-то не так делал
Мне styleguidist хотелось бы попробовать
Вариант с html хорош 👍

**Comment by JorJeG** [comment]
@belodpav нужно сделать pull request, чтобы назначить ревьюеров

**Comment by JorJeG** [comment]
для @jnkbldgn , что мы имеем ввиду, [пример](https://github.com/belodpav/shri-2018-task-3/tree/master/client/src)

**Comment by belodpav** [comment]
Предлагаю изменить архитектурный подход к построению компонентов приложения,
раньше: контейнеры компонентов выделяли в отдельную папку containers
теперь: "контейнер" это одна из технологий в которых будем реализовывать компонент
```
components/
    ...
    Button/
        Button.css - стили к компоненту
        Button.test.js - Тесты к компоненту
        Button.md - документация к компоненту
        Button.html - демонстрация компонента на странице
        Button.view.js - верстка, навешивание событий на элеметы
        Button.js  - логика, получение.обработка данных, событий и т.д.

```

Мы как бы разрабатываем компонент в многомерном пространстве технологий: css, test.js, md, html, и т.д.
